root@0ea2a2d76b33:/app# bash /tests/run-tests.sh; tmux wait -S done
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8793 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [756 B]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [272 kB]
Fetched 9320 kB in 1s (8830 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.88.1-10+deb12u12).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
downloading uv 0.7.13 x86_64-unknown-linux-gnu
no checksums to verify
installing to /root/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
Initialized project `app`
Using CPython 3.10.18 interpreter at: /usr/local/bin/python3.10
Creating virtual environment at: .venv
Resolved 10 packages in 176ms
Prepared 8 packages in 142ms
Installed 8 packages in 22ms
 + exceptiongroup==1.3.0
 + iniconfig==2.1.0
 + packaging==25.0
 + pluggy==1.6.0
 + pygments==2.19.2
 + pytest==8.4.1
 + tomli==2.2.1
 + typing-extensions==4.14.1
Resolved 11 packages in 154ms
Prepared 1 package in 425ms
Installed 1 package in 40ms
 + numpy==2.2.6
===================================================================== test session starts ======================================================================
platform linux -- Python 3.10.18, pytest-8.4.1, pluggy-1.6.0
rootdir: /tests
collected 1 item

../tests/test_outputs.py F                                                                                                                               [100%]

=========================================================================== FAILURES ===========================================================================
______________________________________________________________________ test_right_output _______________________________________________________________________

    def test_right_output():
>       with open("/app/results.json", "r") as f:
E       IsADirectoryError: [Errno 21] Is a directory: '/app/results.json'

/tests/test_outputs.py:9: IsADirectoryError
=================================================================== short test summary info ====================================================================
FAILED ../tests/test_outputs.py::test_right_output - IsADirectoryError: [Errno 21] Is a directory: '/app/results.json'
====================================================================== 1 failed in 0.27s =======================================================================
root@0ea2a2d76b33:/app#
