guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
echo "c.ServerApp.password_identity_provider.hashed_password = 'sha1:$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))")'" >> ~/.ju
pyter/jupyter_notebook_config.py; tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[21] 3279
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:10.154 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:10.158 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:10.163 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:10.166 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:10.171 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:10.480 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:10.498 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:10.500 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:10.501 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:10.505 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:10.505 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:10.505 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:10.569 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:10.574 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:10.575 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:10.575 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:10.575 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:10.575 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:10.576 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:10.576 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:10.576 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:10.576 ServerApp] http://localhost:8827/tree?token=5583bf3edecd3269c0d4eaa721397daf25b2d660fd6f3044
[I 2025-07-15 00:58:10.577 ServerApp]     http://127.0.0.1:8827/tree?token=5583bf3edecd3269c0d4eaa721397daf25b2d660fd6f3044
[I 2025-07-15 00:58:10.577 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:10.581 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:10.582 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3279-open.html
    Or copy and paste one of these URLs:
        http://localhost:8827/tree?token=5583bf3edecd3269c0d4eaa721397daf25b2d660fd6f3044
        http://127.0.0.1:8827/tree?token=5583bf3edecd3269c0d4eaa721397daf25b2d660fd6f3044
[I 2025-07-15 00:58:10.605 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[22] 3333
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:14.601 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:14.605 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:14.609 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:14.611 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:14.615 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:14.852 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:14.867 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:14.869 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:14.870 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:14.873 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:14.873 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:14.874 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:14.923 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:14.927 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:14.928 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:14.928 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:14.928 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:14.928 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:14.929 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:14.929 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:14.929 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:14.929 ServerApp] http://localhost:8844/tree?token=a64f0a4ec7480a5d81e8a23f06ed3fcf9eb21ca33e006680
[I 2025-07-15 00:58:14.929 ServerApp]     http://127.0.0.1:8844/tree?token=a64f0a4ec7480a5d81e8a23f06ed3fcf9eb21ca33e006680
[I 2025-07-15 00:58:14.929 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:14.933 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:14.933 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3333-open.html
    Or copy and paste one of these URLs:
        http://localhost:8844/tree?token=a64f0a4ec7480a5d81e8a23f06ed3fcf9eb21ca33e006680
        http://127.0.0.1:8844/tree?token=a64f0a4ec7480a5d81e8a23f06ed3fcf9eb21ca33e006680
[I 2025-07-15 00:58:14.959 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[23] 3387
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:19.166 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:19.171 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:19.175 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:19.177 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:19.182 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:19.434 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:19.451 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:19.453 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:19.454 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:19.458 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:19.458 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:19.458 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:19.506 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:19.510 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:19.511 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:19.511 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:19.512 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:19.512 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:19.512 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:19.513 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:19.513 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:19.513 ServerApp] http://localhost:8914/tree?token=95b4e4b74d8882de0e74db30cb5739d16b91d99f368101a9
[I 2025-07-15 00:58:19.513 ServerApp]     http://127.0.0.1:8914/tree?token=95b4e4b74d8882de0e74db30cb5739d16b91d99f368101a9
[I 2025-07-15 00:58:19.513 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:19.516 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:19.517 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3387-open.html
    Or copy and paste one of these URLs:
        http://localhost:8914/tree?token=95b4e4b74d8882de0e74db30cb5739d16b91d99f368101a9
        http://127.0.0.1:8914/tree?token=95b4e4b74d8882de0e74db30cb5739d16b91d99f368101a9
[I 2025-07-15 00:58:19.541 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[24] 3441
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:23.417 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:23.421 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:23.426 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:23.429 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:23.434 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:23.693 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:23.709 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:23.711 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:23.712 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:23.715 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:23.715 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:23.716 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:23.766 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:23.770 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:23.771 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:23.771 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:23.771 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:23.771 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:23.772 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:23.772 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:23.772 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:23.772 ServerApp] http://localhost:8949/tree?token=97c96f0120a76c92d58edaf43f7c6d88516c71a1c8beb4ca
[I 2025-07-15 00:58:23.772 ServerApp]     http://127.0.0.1:8949/tree?token=97c96f0120a76c92d58edaf43f7c6d88516c71a1c8beb4ca
[I 2025-07-15 00:58:23.772 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:23.776 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:23.776 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3441-open.html
    Or copy and paste one of these URLs:
        http://localhost:8949/tree?token=97c96f0120a76c92d58edaf43f7c6d88516c71a1c8beb4ca
        http://127.0.0.1:8949/tree?token=97c96f0120a76c92d58edaf43f7c6d88516c71a1c8beb4ca
[I 2025-07-15 00:58:23.798 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[25] 3495
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:28.209 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:28.214 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:28.221 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:28.225 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:28.233 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:28.548 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:28.564 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:28.566 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:28.567 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:28.570 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:28.570 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:28.571 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:28.623 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:28.628 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:28.628 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:28.629 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:28.629 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:28.629 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:28.629 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:28.630 ServerApp] The port 8975 is already in use, trying another port.
[I 2025-07-15 00:58:28.630 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:28.630 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:28.630 ServerApp] http://localhost:8980/tree?token=4906c1413cf3b38cfa8d55eb7e242e166f50e362423b7884
[I 2025-07-15 00:58:28.630 ServerApp]     http://127.0.0.1:8980/tree?token=4906c1413cf3b38cfa8d55eb7e242e166f50e362423b7884
[I 2025-07-15 00:58:28.630 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:28.634 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:28.635 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3495-open.html
    Or copy and paste one of these URLs:
        http://localhost:8980/tree?token=4906c1413cf3b38cfa8d55eb7e242e166f50e362423b7884
        http://127.0.0.1:8980/tree?token=4906c1413cf3b38cfa8d55eb7e242e166f50e362423b7884
[I 2025-07-15 00:58:28.660 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[26] 3548
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:32.757 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:32.761 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:32.766 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:32.769 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:32.775 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:33.101 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:33.118 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:33.120 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:33.122 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:33.125 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:33.125 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:33.125 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:33.183 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:33.187 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:33.188 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:33.188 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:33.188 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:33.189 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:33.189 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:33.190 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:33.190 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:33.190 ServerApp] http://localhost:8796/tree?token=cb0dbf1dd51c21c4e236a06a3fc78472d5cf29606f9b6d40
[I 2025-07-15 00:58:33.190 ServerApp]     http://127.0.0.1:8796/tree?token=cb0dbf1dd51c21c4e236a06a3fc78472d5cf29606f9b6d40
[I 2025-07-15 00:58:33.190 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:33.194 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:33.194 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3548-open.html
    Or copy and paste one of these URLs:
        http://localhost:8796/tree?token=cb0dbf1dd51c21c4e236a06a3fc78472d5cf29606f9b6d40
        http://127.0.0.1:8796/tree?token=cb0dbf1dd51c21c4e236a06a3fc78472d5cf29606f9b6d40
[I 2025-07-15 00:58:33.217 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[27] 3601
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:36.724 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:36.729 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:36.734 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:36.736 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:36.743 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:37.065 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:37.082 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:37.084 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:37.085 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:37.089 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:37.089 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:37.090 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:37.143 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:37.147 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:37.148 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:37.149 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:37.149 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:37.149 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:37.149 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:37.149 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:37.150 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:37.150 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:37.150 ServerApp] http://localhost:8942/tree?token=a0ebeabd068832f53b00b2d850c4f216314d4e083a03e17f
[I 2025-07-15 00:58:37.150 ServerApp]     http://127.0.0.1:8942/tree?token=a0ebeabd068832f53b00b2d850c4f216314d4e083a03e17f
[I 2025-07-15 00:58:37.150 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:37.155 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:37.155 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3601-open.html
    Or copy and paste one of these URLs:
        http://localhost:8942/tree?token=a0ebeabd068832f53b00b2d850c4f216314d4e083a03e17f
        http://127.0.0.1:8942/tree?token=a0ebeabd068832f53b00b2d850c4f216314d4e083a03e17f
[I 2025-07-15 00:58:37.181 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[28] 3655
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:40.784 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:40.789 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:40.794 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:40.797 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:40.803 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:41.144 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:41.163 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:41.165 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:41.166 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:41.170 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:41.170 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:41.170 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:41.231 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:41.235 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:41.236 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:41.236 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:41.237 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:41.237 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:41.237 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:41.238 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:41.238 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:41.238 ServerApp] http://localhost:8935/tree?token=655bc7bcabbc2d4e1a9df9a4fabd85f0104c0919f5e4de3b
[I 2025-07-15 00:58:41.238 ServerApp]     http://127.0.0.1:8935/tree?token=655bc7bcabbc2d4e1a9df9a4fabd85f0104c0919f5e4de3b
[I 2025-07-15 00:58:41.238 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:41.243 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:41.243 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3655-open.html
    Or copy and paste one of these URLs:
        http://localhost:8935/tree?token=655bc7bcabbc2d4e1a9df9a4fabd85f0104c0919f5e4de3b
        http://127.0.0.1:8935/tree?token=655bc7bcabbc2d4e1a9df9a4fabd85f0104c0919f5e4de3b
[I 2025-07-15 00:58:41.267 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[29] 3710
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:45.161 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:45.165 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:45.169 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:45.171 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:45.175 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:45.466 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:45.483 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:45.485 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:45.486 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:45.489 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:45.490 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:45.490 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:45.537 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:45.541 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:45.542 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:45.542 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:45.543 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:45.543 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:45.543 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:45.543 ServerApp] The port 8827 is already in use, trying another port.
[I 2025-07-15 00:58:45.544 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:45.544 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:45.544 ServerApp] http://localhost:8798/tree?token=47751df1e7395d712fae379c324d11dc75d3fdb6f5c7550d
[I 2025-07-15 00:58:45.544 ServerApp]     http://127.0.0.1:8798/tree?token=47751df1e7395d712fae379c324d11dc75d3fdb6f5c7550d
[I 2025-07-15 00:58:45.544 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:45.549 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:45.549 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3710-open.html
    Or copy and paste one of these URLs:
        http://localhost:8798/tree?token=47751df1e7395d712fae379c324d11dc75d3fdb6f5c7550d
        http://127.0.0.1:8798/tree?token=47751df1e7395d712fae379c324d11dc75d3fdb6f5c7550d
[I 2025-07-15 00:58:45.576 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[30] 3764
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:49.760 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:49.764 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:49.769 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:49.772 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:49.777 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:50.079 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:50.095 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:50.097 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:50.099 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:50.102 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:50.102 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:50.102 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:50.151 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:50.156 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:50.157 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:50.157 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:50.157 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:50.157 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:50.158 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:50.158 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:50.158 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:50.158 ServerApp] http://localhost:8969/tree?token=8e30627dac9c70485867be43641f0c5a770eba76b1b4accc
[I 2025-07-15 00:58:50.158 ServerApp]     http://127.0.0.1:8969/tree?token=8e30627dac9c70485867be43641f0c5a770eba76b1b4accc
[I 2025-07-15 00:58:50.158 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:50.163 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:50.163 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3764-open.html
    Or copy and paste one of these URLs:
        http://localhost:8969/tree?token=8e30627dac9c70485867be43641f0c5a770eba76b1b4accc
        http://127.0.0.1:8969/tree?token=8e30627dac9c70485867be43641f0c5a770eba76b1b4accc
[I 2025-07-15 00:58:50.189 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[31] 3817
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:54.254 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:54.258 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:54.263 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:54.266 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:54.271 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:54.577 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:54.594 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:54.596 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:54.597 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:54.600 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:54.600 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:54.601 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:54.656 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:54.660 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:54.661 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:54.661 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:54.661 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:54.662 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:54.662 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:54.662 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:54.662 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:54.662 ServerApp] http://localhost:8968/tree?token=e049d4bb47b84932d1138ddf75cc656f1dc925ac9f4763b1
[I 2025-07-15 00:58:54.662 ServerApp]     http://127.0.0.1:8968/tree?token=e049d4bb47b84932d1138ddf75cc656f1dc925ac9f4763b1
[I 2025-07-15 00:58:54.662 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:54.666 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:54.666 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3817-open.html
    Or copy and paste one of these URLs:
        http://localhost:8968/tree?token=e049d4bb47b84932d1138ddf75cc656f1dc925ac9f4763b1
        http://127.0.0.1:8968/tree?token=e049d4bb47b84932d1138ddf75cc656f1dc925ac9f4763b1
[I 2025-07-15 00:58:54.690 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[32] 3870
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:58:58.427 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:58:58.431 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:58:58.436 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:58:58.438 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:58:58.444 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:58:58.783 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:58:58.801 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:58:58.803 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:58:58.803 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:58:58.806 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:58:58.807 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:58:58.807 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:58:58.860 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:58:58.865 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:58:58.865 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:58:58.866 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:58:58.866 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:58:58.866 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:58:58.866 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:58:58.867 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:58:58.867 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:58:58.867 ServerApp] http://localhost:8987/tree?token=b1a6be0cf76135c08b8fc2e8580b65a48496f82c7d9f7960
[I 2025-07-15 00:58:58.867 ServerApp]     http://127.0.0.1:8987/tree?token=b1a6be0cf76135c08b8fc2e8580b65a48496f82c7d9f7960
[I 2025-07-15 00:58:58.867 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:58:58.872 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:58:58.872 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3870-open.html
    Or copy and paste one of these URLs:
        http://localhost:8987/tree?token=b1a6be0cf76135c08b8fc2e8580b65a48496f82c7d9f7960
        http://127.0.0.1:8987/tree?token=b1a6be0cf76135c08b8fc2e8580b65a48496f82c7d9f7960
[I 2025-07-15 00:58:58.895 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[33] 3923
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:02.727 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:02.731 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:02.736 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:02.738 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:02.744 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:03.051 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:03.067 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:03.069 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:03.070 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:03.073 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:03.073 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:03.074 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:03.120 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:03.125 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:03.125 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:03.125 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:03.126 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:03.126 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:03.126 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:03.127 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:03.127 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:03.127 ServerApp] http://localhost:8915/tree?token=5493adc29debc95f3c6425e2027279c435c0b314eb73aa5e
[I 2025-07-15 00:59:03.127 ServerApp]     http://127.0.0.1:8915/tree?token=5493adc29debc95f3c6425e2027279c435c0b314eb73aa5e
[I 2025-07-15 00:59:03.127 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:03.130 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:03.130 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3923-open.html
    Or copy and paste one of these URLs:
        http://localhost:8915/tree?token=5493adc29debc95f3c6425e2027279c435c0b314eb73aa5e
        http://127.0.0.1:8915/tree?token=5493adc29debc95f3c6425e2027279c435c0b314eb73aa5e
[I 2025-07-15 00:59:03.152 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[34] 3977
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:06.683 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:06.688 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:06.692 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:06.694 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:06.699 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:07.015 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:07.033 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:07.035 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:07.036 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:07.040 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:07.040 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:07.040 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:07.103 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:07.108 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:07.108 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:07.109 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:07.109 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:07.109 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:07.109 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:07.110 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:07.110 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:07.110 ServerApp] http://localhost:8860/tree?token=4f8a9e131c13e37f00caeb2904197c0235b101da6410734f
[I 2025-07-15 00:59:07.110 ServerApp]     http://127.0.0.1:8860/tree?token=4f8a9e131c13e37f00caeb2904197c0235b101da6410734f
[I 2025-07-15 00:59:07.110 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:07.115 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:07.115 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-3977-open.html
    Or copy and paste one of these URLs:
        http://localhost:8860/tree?token=4f8a9e131c13e37f00caeb2904197c0235b101da6410734f
        http://127.0.0.1:8860/tree?token=4f8a9e131c13e37f00caeb2904197c0235b101da6410734f
[I 2025-07-15 00:59:07.140 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[35] 4031
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:11.317 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:11.322 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:11.326 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:11.329 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:11.335 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:11.664 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:11.681 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:11.684 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:11.685 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:11.689 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:11.689 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:11.689 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:11.751 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:11.755 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:11.756 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:11.756 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:11.756 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:11.756 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:11.757 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:11.757 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:11.757 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:11.757 ServerApp] http://localhost:8936/tree?token=ec1d680edcafaad4dc8114fe47a591e1aa9a5847fedc2e01
[I 2025-07-15 00:59:11.757 ServerApp]     http://127.0.0.1:8936/tree?token=ec1d680edcafaad4dc8114fe47a591e1aa9a5847fedc2e01
[I 2025-07-15 00:59:11.757 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:11.762 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:11.762 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4031-open.html
    Or copy and paste one of these URLs:
        http://localhost:8936/tree?token=ec1d680edcafaad4dc8114fe47a591e1aa9a5847fedc2e01
        http://127.0.0.1:8936/tree?token=ec1d680edcafaad4dc8114fe47a591e1aa9a5847fedc2e01
[I 2025-07-15 00:59:11.785 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[36] 4085
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:15.928 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:15.932 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:15.937 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:15.940 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:15.946 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:16.257 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:16.275 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:16.277 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:16.278 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:16.281 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:16.282 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:16.282 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:16.343 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:16.347 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:16.348 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:16.348 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:16.348 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:16.349 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:16.349 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:16.349 ServerApp] The port 8989 is already in use, trying another port.
[I 2025-07-15 00:59:16.349 ServerApp] The port 8796 is already in use, trying another port.
[I 2025-07-15 00:59:16.350 ServerApp] The port 8922 is already in use, trying another port.
[I 2025-07-15 00:59:16.350 ServerApp] The port 8969 is already in use, trying another port.
[I 2025-07-15 00:59:16.350 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:16.350 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:16.351 ServerApp] http://localhost:8896/tree?token=970d0797c9eaf041346aa8d2fe7de7b878d2ce25533208cd
[I 2025-07-15 00:59:16.351 ServerApp]     http://127.0.0.1:8896/tree?token=970d0797c9eaf041346aa8d2fe7de7b878d2ce25533208cd
[I 2025-07-15 00:59:16.351 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:16.355 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:16.355 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4085-open.html
    Or copy and paste one of these URLs:
        http://localhost:8896/tree?token=970d0797c9eaf041346aa8d2fe7de7b878d2ce25533208cd
        http://127.0.0.1:8896/tree?token=970d0797c9eaf041346aa8d2fe7de7b878d2ce25533208cd
[I 2025-07-15 00:59:16.380 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[37] 4138
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:19.815 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:19.819 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:19.823 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:19.825 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:19.829 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:20.147 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:20.167 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:20.169 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:20.170 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:20.174 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:20.174 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:20.174 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:20.232 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:20.237 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:20.237 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:20.238 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:20.238 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:20.238 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:20.239 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:20.240 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:20.240 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:20.240 ServerApp] http://localhost:8809/tree?token=537477775cbb15b625802ba3f17e3a016340ac30db827b23
[I 2025-07-15 00:59:20.240 ServerApp]     http://127.0.0.1:8809/tree?token=537477775cbb15b625802ba3f17e3a016340ac30db827b23
[I 2025-07-15 00:59:20.240 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:20.245 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:20.245 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4138-open.html
    Or copy and paste one of these URLs:
        http://localhost:8809/tree?token=537477775cbb15b625802ba3f17e3a016340ac30db827b23
        http://127.0.0.1:8809/tree?token=537477775cbb15b625802ba3f17e3a016340ac30db827b23
[I 2025-07-15 00:59:20.268 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[38] 4192
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:24.329 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:24.334 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:24.339 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:24.341 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:24.347 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:24.662 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:24.680 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:24.682 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:24.683 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:24.688 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:24.688 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:24.689 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:24.748 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:24.752 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:24.753 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:24.753 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:24.753 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:24.754 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:24.754 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:24.754 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:24.754 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:24.754 ServerApp] http://localhost:8875/tree?token=c78a3bc2b40918020e371807cca600f3bfc48e679986290a
[I 2025-07-15 00:59:24.754 ServerApp]     http://127.0.0.1:8875/tree?token=c78a3bc2b40918020e371807cca600f3bfc48e679986290a
[I 2025-07-15 00:59:24.754 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:24.759 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:24.759 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4192-open.html
    Or copy and paste one of these URLs:
        http://localhost:8875/tree?token=c78a3bc2b40918020e371807cca600f3bfc48e679986290a
        http://127.0.0.1:8875/tree?token=c78a3bc2b40918020e371807cca600f3bfc48e679986290a
[I 2025-07-15 00:59:24.781 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[39] 4246
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:29.403 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:29.408 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:29.414 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:29.417 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:29.423 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:29.748 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:29.766 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:29.768 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:29.769 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:29.773 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:29.773 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:29.773 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:29.823 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:29.828 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:29.828 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:29.828 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:29.829 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:29.829 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:29.829 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:29.830 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:29.830 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:29.830 ServerApp] http://localhost:8877/tree?token=dbba9bfe474183eecb36cd36d503b1b4ecc286216dd698c6
[I 2025-07-15 00:59:29.830 ServerApp]     http://127.0.0.1:8877/tree?token=dbba9bfe474183eecb36cd36d503b1b4ecc286216dd698c6
[I 2025-07-15 00:59:29.830 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:29.833 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:29.833 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4246-open.html
    Or copy and paste one of these URLs:
        http://localhost:8877/tree?token=dbba9bfe474183eecb36cd36d503b1b4ecc286216dd698c6
        http://127.0.0.1:8877/tree?token=dbba9bfe474183eecb36cd36d503b1b4ecc286216dd698c6
[I 2025-07-15 00:59:29.857 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[40] 4300
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:34.926 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:34.930 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:34.934 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:34.936 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:34.940 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:35.215 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:35.233 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:35.235 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:35.236 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:35.239 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:35.239 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:35.240 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:35.295 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:35.300 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:35.301 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:35.301 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:35.301 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:35.301 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:35.302 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:35.302 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:35.302 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:35.302 ServerApp] http://localhost:8962/tree?token=87229fc571e8c29f8c9a118ef30fb38667ba7e31a9fc8a69
[I 2025-07-15 00:59:35.302 ServerApp]     http://127.0.0.1:8962/tree?token=87229fc571e8c29f8c9a118ef30fb38667ba7e31a9fc8a69
[I 2025-07-15 00:59:35.302 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:35.307 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:35.307 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4300-open.html
    Or copy and paste one of these URLs:
        http://localhost:8962/tree?token=87229fc571e8c29f8c9a118ef30fb38667ba7e31a9fc8a69
        http://127.0.0.1:8962/tree?token=87229fc571e8c29f8c9a118ef30fb38667ba7e31a9fc8a69
[I 2025-07-15 00:59:35.332 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[41] 4354
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:39.354 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:39.358 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:39.364 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:39.367 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:39.373 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:39.703 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:39.720 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:39.722 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:39.723 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:39.727 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:39.727 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:39.727 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:39.785 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:39.789 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:39.790 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:39.790 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:39.790 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:39.791 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:39.791 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:39.791 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:39.791 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:39.791 ServerApp] http://localhost:8910/tree?token=47b99162e28733bfcf57f2aa11961a2f83cd471f56a5bd9b
[I 2025-07-15 00:59:39.791 ServerApp]     http://127.0.0.1:8910/tree?token=47b99162e28733bfcf57f2aa11961a2f83cd471f56a5bd9b
[I 2025-07-15 00:59:39.791 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:39.796 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:39.796 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4354-open.html
    Or copy and paste one of these URLs:
        http://localhost:8910/tree?token=47b99162e28733bfcf57f2aa11961a2f83cd471f56a5bd9b
        http://127.0.0.1:8910/tree?token=47b99162e28733bfcf57f2aa11961a2f83cd471f56a5bd9b
[I 2025-07-15 00:59:39.820 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[42] 4408
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:44.801 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:44.806 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:44.811 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:44.813 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:44.818 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:45.159 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:45.179 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:45.181 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:45.182 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:45.186 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:45.186 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:45.186 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:45.258 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:45.264 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:45.265 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:45.265 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:45.266 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:45.266 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:45.266 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:45.267 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:45.267 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:45.267 ServerApp] http://localhost:8924/tree?token=5494df0120723b82caeda6c8d462edb65618ff307e90a7f4
[I 2025-07-15 00:59:45.267 ServerApp]     http://127.0.0.1:8924/tree?token=5494df0120723b82caeda6c8d462edb65618ff307e90a7f4
[I 2025-07-15 00:59:45.267 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:45.273 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:45.273 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4408-open.html
    Or copy and paste one of these URLs:
        http://localhost:8924/tree?token=5494df0120723b82caeda6c8d462edb65618ff307e90a7f4
        http://127.0.0.1:8924/tree?token=5494df0120723b82caeda6c8d462edb65618ff307e90a7f4
[I 2025-07-15 00:59:45.300 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[43] 4462
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:50.321 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:50.326 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:50.332 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:50.335 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:50.342 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:50.675 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:50.694 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:50.697 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:50.698 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:50.701 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:50.701 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:50.702 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:50.766 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:50.771 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:50.772 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:50.772 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:50.772 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:50.773 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:50.773 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:50.773 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:50.773 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:50.774 ServerApp] http://localhost:8859/tree?token=faee690ea73c8835ea066182e92c14ab271fde3eb11b420d
[I 2025-07-15 00:59:50.774 ServerApp]     http://127.0.0.1:8859/tree?token=faee690ea73c8835ea066182e92c14ab271fde3eb11b420d
[I 2025-07-15 00:59:50.774 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:50.778 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:50.778 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4462-open.html
    Or copy and paste one of these URLs:
        http://localhost:8859/tree?token=faee690ea73c8835ea066182e92c14ab271fde3eb11b420d
        http://127.0.0.1:8859/tree?token=faee690ea73c8835ea066182e92c14ab271fde3eb11b420d
[I 2025-07-15 00:59:50.802 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[44] 4516
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:55.436 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:55.441 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:55.446 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:55.449 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:55.455 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 00:59:55.791 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 00:59:55.812 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 00:59:55.815 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 00:59:55.816 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 00:59:55.820 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 00:59:55.820 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 00:59:55.821 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 00:59:55.886 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 00:59:55.891 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 00:59:55.892 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 00:59:55.892 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 00:59:55.892 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 00:59:55.893 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 00:59:55.893 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 00:59:55.893 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 00:59:55.893 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 00:59:55.894 ServerApp] http://localhost:8940/tree?token=366e34894e9e309edfa0cffc6fc510c40d984915e8b30795
[I 2025-07-15 00:59:55.894 ServerApp]     http://127.0.0.1:8940/tree?token=366e34894e9e309edfa0cffc6fc510c40d984915e8b30795
[I 2025-07-15 00:59:55.894 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 00:59:55.898 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 00:59:55.898 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4516-open.html
    Or copy and paste one of these URLs:
        http://localhost:8940/tree?token=366e34894e9e309edfa0cffc6fc510c40d984915e8b30795
        http://127.0.0.1:8940/tree?token=366e34894e9e309edfa0cffc6fc510c40d984915e8b30795
[I 2025-07-15 00:59:55.924 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[45] 4569
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 00:59:59.891 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 00:59:59.896 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 00:59:59.901 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 00:59:59.903 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 00:59:59.907 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 01:00:00.155 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 01:00:00.174 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 01:00:00.176 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 01:00:00.177 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 01:00:00.181 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 01:00:00.181 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 01:00:00.182 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 01:00:00.240 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 01:00:00.245 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 01:00:00.246 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 01:00:00.246 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 01:00:00.246 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 01:00:00.247 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 01:00:00.247 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 01:00:00.247 ServerApp] The port 8859 is already in use, trying another port.
[I 2025-07-15 01:00:00.248 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 01:00:00.248 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 01:00:00.248 ServerApp] http://localhost:8920/tree?token=7688ee859fa28714af79fd9be3c21b9a08c3cac049ca1bb5
[I 2025-07-15 01:00:00.248 ServerApp]     http://127.0.0.1:8920/tree?token=7688ee859fa28714af79fd9be3c21b9a08c3cac049ca1bb5
[I 2025-07-15 01:00:00.248 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 01:00:00.252 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 01:00:00.252 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4569-open.html
    Or copy and paste one of these URLs:
        http://localhost:8920/tree?token=7688ee859fa28714af79fd9be3c21b9a08c3cac049ca1bb5
        http://127.0.0.1:8920/tree?token=7688ee859fa28714af79fd9be3c21b9a08c3cac049ca1bb5
[I 2025-07-15 01:00:00.277 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[46] 4622
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 01:00:05.382 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 01:00:05.386 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 01:00:05.392 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 01:00:05.395 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 01:00:05.401 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 01:00:05.769 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 01:00:05.786 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 01:00:05.788 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 01:00:05.789 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 01:00:05.793 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 01:00:05.793 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 01:00:05.793 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 01:00:05.851 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 01:00:05.856 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 01:00:05.857 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 01:00:05.857 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 01:00:05.858 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 01:00:05.858 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 01:00:05.858 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 01:00:05.859 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 01:00:05.859 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 01:00:05.859 ServerApp] http://localhost:8946/tree?token=384a672ec45bdb782d8243a12973a317bd0fddcc0aeb9057
[I 2025-07-15 01:00:05.859 ServerApp]     http://127.0.0.1:8946/tree?token=384a672ec45bdb782d8243a12973a317bd0fddcc0aeb9057
[I 2025-07-15 01:00:05.859 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 01:00:05.864 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 01:00:05.864 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4622-open.html
    Or copy and paste one of these URLs:
        http://localhost:8946/tree?token=384a672ec45bdb782d8243a12973a317bd0fddcc0aeb9057
        http://127.0.0.1:8946/tree?token=384a672ec45bdb782d8243a12973a317bd0fddcc0aeb9057
[I 2025-07-15 01:00:05.888 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[47] 4676
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 01:00:11.207 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 01:00:11.211 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 01:00:11.216 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 01:00:11.219 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 01:00:11.225 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 01:00:11.571 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 01:00:11.591 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 01:00:11.594 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 01:00:11.595 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 01:00:11.599 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 01:00:11.599 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 01:00:11.600 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 01:00:11.667 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 01:00:11.671 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 01:00:11.672 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 01:00:11.672 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 01:00:11.672 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 01:00:11.673 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 01:00:11.673 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 01:00:11.674 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 01:00:11.674 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 01:00:11.674 ServerApp] http://localhost:8965/tree?token=6b54f668864c07be5ec6fd47a1755903343da76d282ddb98
[I 2025-07-15 01:00:11.674 ServerApp]     http://127.0.0.1:8965/tree?token=6b54f668864c07be5ec6fd47a1755903343da76d282ddb98
[I 2025-07-15 01:00:11.674 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 01:00:11.679 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 01:00:11.679 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4676-open.html
    Or copy and paste one of these URLs:
        http://localhost:8965/tree?token=6b54f668864c07be5ec6fd47a1755903343da76d282ddb98
        http://127.0.0.1:8965/tree?token=6b54f668864c07be5ec6fd47a1755903343da76d282ddb98
[I 2025-07-15 01:00:11.705 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[48] 4730
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 01:00:16.715 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 01:00:16.720 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 01:00:16.725 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 01:00:16.729 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 01:00:16.735 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 01:00:17.094 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 01:00:17.113 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 01:00:17.116 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 01:00:17.117 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 01:00:17.120 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 01:00:17.120 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 01:00:17.120 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 01:00:17.178 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 01:00:17.183 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 01:00:17.183 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 01:00:17.184 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 01:00:17.184 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 01:00:17.184 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 01:00:17.185 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 01:00:17.185 ServerApp] The port 8915 is already in use, trying another port.
[I 2025-07-15 01:00:17.185 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 01:00:17.185 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 01:00:17.186 ServerApp] http://localhost:8898/tree?token=f2e45cfa405f689097a359455bf99b372f05427d508a41e2
[I 2025-07-15 01:00:17.186 ServerApp]     http://127.0.0.1:8898/tree?token=f2e45cfa405f689097a359455bf99b372f05427d508a41e2
[I 2025-07-15 01:00:17.186 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 01:00:17.190 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 01:00:17.190 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4730-open.html
    Or copy and paste one of these URLs:
        http://localhost:8898/tree?token=f2e45cfa405f689097a359455bf99b372f05427d508a41e2
        http://127.0.0.1:8898/tree?token=f2e45cfa405f689097a359455bf99b372f05427d508a41e2
[I 2025-07-15 01:00:17.215 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[49] 4784
(jupyter_env) root@99a641a51835:/app# [I 2025-07-15 01:00:22.643 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 01:00:22.649 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 01:00:22.656 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 01:00:22.662 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 01:00:22.671 ServerApp] notebook | extension was successfully linked.
[I 2025-07-15 01:00:23.130 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-15 01:00:23.155 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 01:00:23.158 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 01:00:23.159 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 01:00:23.163 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 01:00:23.163 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 01:00:23.165 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 01:00:23.248 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 01:00:23.256 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 01:00:23.257 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 01:00:23.257 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 01:00:23.258 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 01:00:23.258 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 01:00:23.258 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 01:00:23.259 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 01:00:23.259 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 01:00:23.259 ServerApp] http://localhost:8816/tree?token=c87306bd9ea4027dbb27b0b331e3947b5bbff08174a1ea43
[I 2025-07-15 01:00:23.259 ServerApp]     http://127.0.0.1:8816/tree?token=c87306bd9ea4027dbb27b0b331e3947b5bbff08174a1ea43
[I 2025-07-15 01:00:23.259 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 01:00:23.265 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 01:00:23.265 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4784-open.html
    Or copy and paste one of these URLs:
        http://localhost:8816/tree?token=c87306bd9ea4027dbb27b0b331e3947b5bbff08174a1ea43
        http://127.0.0.1:8816/tree?token=c87306bd9ea4027dbb27b0b331e3947b5bbff08174a1ea43
[I 2025-07-15 01:00:23.300 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
hashed_password=$(python3 -c "from notebook.auth import passwd; print(passwd('benchmarkpass'))"); tmux wait -S done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from notebook.auth import passwd; print(passwd('benchmarkpass'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.auth'
(jupyter_env) root@99a641a51835:/app# echo "c.ServerApp.password_identity_provider.hashed_password = '$hashed_password'" >> ~/.jupyter/jupyter_notebook_config.p
y; tmux wait -S done
(jupyter_env) root@99a641a51835:/app# jupyter notebook --notebook-dir=/app --allow-root &
[50] 4840
(jupyter_env) root@99a641a51835:/app# bash /tests/run-tests.sh; tmux wait -S done
[I 2025-07-15 01:00:27.474 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-15 01:00:27.479 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-15 01:00:27.485 ServerApp] jupyterlab | extension was successfully linked.
[E 2025-07-15 01:00:27.489 JupyterNotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 622, in load_config
        self._read_file_as_dict()
        ~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/app/jupyter_env/lib/python3.13/site-packages/traitlets/config/loader.py", line 655, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa: S102
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.jupyter/jupyter_notebook_config.py", line 1134, in <module>
        c.ServerApp.password_identity_provider.hashed_password = ''
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'hashed_password' and no __dict__ for setting new attributes
[I 2025-07-15 01:00:27.498 ServerApp] notebook | extension was successfully linked.
Collecting pytest==8.4.1
  Downloading pytest-8.4.1-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: requests==2.32.4 in ./jupyter_env/lib/python3.13/site-packages (2.32.4)
Collecting iniconfig>=1 (from pytest==8.4.1)
  Downloading iniconfig-2.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: packaging>=20 in ./jupyter_env/lib/python3.13/site-packages (from pytest==8.4.1) (25.0)
Collecting pluggy<2,>=1.5 (from pytest==8.4.1)
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pygments>=2.7.2 in ./jupyter_env/lib/python3.13/site-packages (from pytest==8.4.1) (2.19.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./jupyter_env/lib/python3.13/site-packages (from requests==2.32.4) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./jupyter_env/lib/python3.13/site-packages (from requests==2.32.4) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./jupyter_env/lib/python3.13/site-packages (from requests==2.32.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./jupyter_env/lib/python3.13/site-packages (from requests==2.32.4) (2025.7.14)
Downloading pytest-8.4.1-py3-none-any.whl (365 kB)
Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
[I 2025-07-15 01:00:27.828 ServerApp] notebook_shim | extension was successfully linked.
Downloading iniconfig-2.1.0-py3-none-any.whl (6.0 kB)
[I 2025-07-15 01:00:27.844 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-15 01:00:27.846 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-15 01:00:27.847 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-15 01:00:27.851 LabApp] JupyterLab extension loaded from /app/jupyter_env/lib/python3.13/site-packages/jupyterlab
[I 2025-07-15 01:00:27.851 LabApp] JupyterLab application directory is /app/jupyter_env/share/jupyter/lab
[I 2025-07-15 01:00:27.852 LabApp] Extension Manager is 'pypi'.
[I 2025-07-15 01:00:27.929 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-15 01:00:27.934 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-15 01:00:27.935 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-07-15 01:00:27.936 ServerApp] The port 8889 is already in use, trying another port.
[I 2025-07-15 01:00:27.936 ServerApp] The port 8890 is already in use, trying another port.
[I 2025-07-15 01:00:27.936 ServerApp] The port 8891 is already in use, trying another port.
[I 2025-07-15 01:00:27.936 ServerApp] The port 8892 is already in use, trying another port.
[I 2025-07-15 01:00:27.937 ServerApp] The port 8789 is already in use, trying another port.
[I 2025-07-15 01:00:27.937 ServerApp] The port 8860 is already in use, trying another port.
[I 2025-07-15 01:00:27.937 ServerApp] Serving notebooks from local directory: /app
[I 2025-07-15 01:00:27.938 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-15 01:00:27.938 ServerApp] http://localhost:8851/tree?token=ca76f6931ba47c132c0373255473d94105a4d24738b82fad
[I 2025-07-15 01:00:27.938 ServerApp]     http://127.0.0.1:8851/tree?token=ca76f6931ba47c132c0373255473d94105a4d24738b82fad
[I 2025-07-15 01:00:27.938 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2025-07-15 01:00:27.942 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2025-07-15 01:00:27.942 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-4840-open.html
    Or copy and paste one of these URLs:
        http://localhost:8851/tree?token=ca76f6931ba47c132c0373255473d94105a4d24738b82fad
        http://127.0.0.1:8851/tree?token=ca76f6931ba47c132c0373255473d94105a4d24738b82fad
[I 2025-07-15 01:00:27.969 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver
, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-lan
guage-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
Installing collected packages: pluggy, iniconfig, pytest
Successfully installed iniconfig-2.1.0 pluggy-1.6.0 pytest-8.4.1
===================================================================== test session starts ======================================================================
platform linux -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0 -- /app/jupyter_env/bin/python
cachedir: .pytest_cache
rootdir: /tests
plugins: anyio-4.9.0
collected 4 items

../tests/test_outputs.py::test_jupyter_server_running [I 2025-07-15 01:00:29.214 ServerApp] 302 GET / (@127.0.0.1) 0.94ms
[I 2025-07-15 01:00:29.221 JupyterNotebookApp] 302 GET /tree (@127.0.0.1) 0.99ms
PASSED                                                                                             [ 25%]
../tests/test_outputs.py::test_jupyter_config_exists PASSED                                                                                              [ 50%]
../tests/test_outputs.py::test_sample_notebook_exists FAILED                                                                                             [ 75%]
../tests/test_outputs.py::test_password_authentication FAILED                                                                                            [100%]

=========================================================================== FAILURES ===========================================================================
_________________________________________________________________ test_sample_notebook_exists __________________________________________________________________

s = "# Jupyter Notebook\nThis notebook provides an interactive environment for computing and data visualization.\\n\nimpor...pyplot as plt\nx = np.linspace(0, 2
 * np.pi, 100)\ny = np.sin(x)\nplt.plot(x, y)\nplt.title('Sine Wave')\nplt.show()\n"
kwargs = {}, message = 'Notebook does not appear to be JSON: "# Jupyter Notebook\\nThis notebook provi...'

    def parse_json(s, **kwargs):
        """Parse a JSON string into a dict."""
        try:
>           nb_dict = json.loads(s, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^

jupyter_env/lib/python3.13/site-packages/nbformat/reader.py:19:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.13/json/__init__.py:346: in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/local/lib/python3.13/json/decoder.py:345: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <json.decoder.JSONDecoder object at 0x7fc4b032f0e0>
s = "# Jupyter Notebook\nThis notebook provides an interactive environment for computing and data visualization.\\n\nimpor...pyplot as plt\nx = np.linspace(0, 2
 * np.pi, 100)\ny = np.sin(x)\nplt.plot(x, y)\nplt.title('Sine Wave')\nplt.show()\n"
idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.

        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.

        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/usr/local/lib/python3.13/json/decoder.py:363: JSONDecodeError

The above exception was the direct cause of the following exception:

    def test_sample_notebook_exists():
        """Test that the sample notebook exists with required cells."""
        notebook_path = Path("/app/test_notebook.ipynb")
        assert notebook_path.exists(), "Sample notebook does not exist"

        # Load and parse the notebook
>       notebook = nbformat.read(notebook_path, as_version=4)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tests/test_outputs.py:61:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
jupyter_env/lib/python3.13/site-packages/nbformat/__init__.py:172: in read
    return reads(f.read(), as_version, capture_validation_error, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jupyter_env/lib/python3.13/site-packages/nbformat/__init__.py:92: in reads
    nb = reader.reads(s, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
jupyter_env/lib/python3.13/site-packages/nbformat/reader.py:75: in reads
    nb_dict = parse_json(s, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

s = "# Jupyter Notebook\nThis notebook provides an interactive environment for computing and data visualization.\\n\nimpor...pyplot as plt\nx = np.linspace(0, 2
 * np.pi, 100)\ny = np.sin(x)\nplt.plot(x, y)\nplt.title('Sine Wave')\nplt.show()\n"
kwargs = {}, message = 'Notebook does not appear to be JSON: "# Jupyter Notebook\\nThis notebook provi...'

    def parse_json(s, **kwargs):
        """Parse a JSON string into a dict."""
        try:
            nb_dict = json.loads(s, **kwargs)
        except ValueError as e:
            message = f"Notebook does not appear to be JSON: {s!r}"
            # Limit the error message to 80 characters.  Display whatever JSON will fit.
            if len(message) > 80:
                message = message[:77] + "..."
>           raise NotJSONError(message) from e
E           nbformat.reader.NotJSONError: Notebook does not appear to be JSON: "# Jupyter Notebook\nThis notebook provi...

jupyter_env/lib/python3.13/site-packages/nbformat/reader.py:25: NotJSONError
_________________________________________________________________ test_password_authentication _________________________________________________________________

    def test_password_authentication():
        """Test that password authentication is configured correctly."""

        config_path = Path.home() / ".jupyter" / "jupyter_notebook_config.py"
        config_content = config_path.read_text()

        # Extract the password hash from config
        import re

        password_match = re.search(r"c.NotebookApp.password = '(.*?)'", config_content)
        assert password_match, "Cannot find password hash in configuration"

        # Verify the password hash is valid for 'benchmarkpass'
        password_hash = password_match.group(1)
        expected_password = "benchmarkpass"

        # Generate a new hash with the expected password and compare formats
        # We can't directly compare hashes due to salt, but we can verify format
        from jupyter_server.auth.security import passwd_check

>       assert passwd_check(password_hash, expected_password), (
            "Password hash does not match expected password"
        )
E       AssertionError: Password hash does not match expected password
E       assert False
E        +  where False = <function passwd_check at 0x7fc4ae4993a0>('sha1:', 'benchmarkpass')

/tests/test_outputs.py:106: AssertionError
======================================================================= warnings summary =======================================================================
test_outputs.py::test_password_authentication
  /app/jupyter_env/lib/python3.13/site-packages/jupyter_server/auth/security.py:14: DeprecationWarning: Jupyter is migrating its paths to use standard platformd
irs
  given by the platformdirs library.  To remove this warning and
  see the appropriate new directories, set the environment variable
  `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
  The use of platformdirs will be the default in `jupyter_core` v6
    from jupyter_core.paths import jupyter_config_dir

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================ PASSES ============================================================================
=================================================================== short test summary info ====================================================================
PASSED ../tests/test_outputs.py::test_jupyter_server_running
PASSED ../tests/test_outputs.py::test_jupyter_config_exists
FAILED ../tests/test_outputs.py::test_sample_notebook_exists - nbformat.reader.NotJSONError: Notebook does not appear to be JSON: "# Jupyter Notebook\nThis note
book provi...
FAILED ../tests/test_outputs.py::test_password_authentication - AssertionError: Password hash does not match expected password
============================================================ 2 failed, 2 passed, 1 warning in 0.45s ============================================================
(jupyter_env) root@99a641a51835:/app#
